/**
 * CatalogAI Benchmark Dataset and Ground Truth Knowledge Base
 * Strictly complies with Zero-Hallucination, Evidence Traceability, and Confidence Scoring rules.
 */

export const SAMPLE_SUPPLIER_INPUTS = [
  {
    id: 'test-a',
    brand: 'Bosch',
    partNumber: 'GSR 120-LI',
    shortDescription: '12v drill driver cordless',
    badge: 'Test A: Good Product',
    testType: 'good_product',
    scenario: 'Exact OEM match with full datasheet evidence and high confidence.',
  },
  {
    id: 'test-b',
    brand: 'Unknown',
    partNumber: 'ABC-123',
    shortDescription: 'industrial tool',
    badge: 'Test B: Incomplete (Zero Hallucination)',
    testType: 'incomplete_product',
    scenario: 'Incomplete / unverified product. AI returns "Not Found" without inventing specs.',
  },
  {
    id: 'test-c',
    brand: 'Bosch',
    partNumber: 'GSR 120-LI',
    shortDescription: '18v heavy duty cordless drill driver brushless',
    badge: 'Test C: Conflicting Data',
    testType: 'conflicting_data',
    scenario: 'Supplier claims 18V, but OEM datasheet is 12V. Flags conflict without choosing blindly.',
  },
  {
    id: 'sample-makita',
    brand: 'Makita',
    partNumber: 'DHP482',
    shortDescription: '18v cordless hammer drill bare tool',
    badge: 'Makita LXT Combi',
    testType: 'standard',
  },
  {
    id: 'sample-dewalt',
    brand: 'DeWalt',
    partNumber: 'DCD771',
    shortDescription: '20v cordless drill driver 1/2 in chuck',
    badge: 'DeWalt 20V Max',
    testType: 'standard',
  },
  {
    id: 'sample-fluke',
    brand: 'Fluke',
    partNumber: '117',
    shortDescription: 'electricians true rms multimeter voltalert non-contact voltage',
    badge: 'Fluke Multimeter',
    testType: 'standard',
  },
  {
    id: 'sample-stanley',
    brand: 'Stanley',
    partNumber: 'STHT10424',
    shortDescription: 'utility knife quick blade change ergonomic grip',
    badge: 'Hand Tools',
    testType: 'standard',
  },
  {
    id: 'sample-3m',
    brand: '3M',
    partNumber: 'H-700',
    shortDescription: 'safety helmet 4-point ratchet suspension white',
    badge: 'Safety Gear',
    testType: 'standard',
  },
  {
    id: 'sample-frigidaire',
    brand: 'Frigidaire',
    partNumber: 'PDSH4816AF',
    shortDescription: 'PDSH4816AF Dishwasher SS - Display Only Professional Series With CleanBoost',
    badge: 'Built-in Dishwasher',
    testType: 'enterprise',
  },
];

export const INITIAL_PRODUCTS = [
  // 1. TEST A: Good Product (Bosch GSR 120-LI)
  {
    id: 'prod-test-a',
    brand: 'Bosch',
    partNumber: 'GSR 120-LI',
    inputDescription: '12v drill driver cordless',
    productTitle: 'Bosch GSR 120-LI Professional 12V Cordless Drill Driver',
    category: ['Tools & Hardware', 'Power Tools', 'Drills', 'Cordless Drills'],
    categoryPath: 'Tools & Hardware > Power Tools > Drills > Cordless Drills',
    categoryStatus: 'Verified',
    confidence: 96,
    status: 'Ready for Review',
    reviewStatus: 'Validated',
    processedAt: '2026-08-16T18:32:00Z',
    description:
      'Bosch GSR 120-LI 12 V cordless drill driver with 2-speed gearbox (0–400 / 0–1500 RPM), 10 mm keyless chuck, 30 Nm maximum torque, and Electronic Cell Protection (ECP).',
    productIdentification: {
      brand: 'Bosch',
      partNumber: 'GSR 120-LI',
      matchedProduct: 'Bosch GSR 120-LI Professional Cordless Drill/Driver',
      matchType: 'exact',
      confidence: 98,
      evidence: 'Exact OEM part number match in Bosch Power Tools Global Master Catalog (GTIN 3165140954549).',
      source: 'manufacturer',
      sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
    },
    attributes: [
      {
        id: 'attr-a-1',
        name: 'Voltage Rating',
        value: '12 V',
        confidence: 98,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Battery voltage: 12 V (also extracted from supplier text "12v")',
        reason: 'Directly supported by official manufacturer specification and supplier text.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-2',
        name: 'Chuck Size',
        value: '10 mm',
        confidence: 96,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Chuck capacity, min./max.: 0.8 / 10 mm keyless three-jaw chuck',
        reason: 'Directly supported by manufacturer technical specification.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-3',
        name: 'Battery Chemistry',
        value: 'Lithium-Ion (Li-Ion)',
        confidence: 95,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Battery type: Lithium-ion Bosch 12V Professional Platform',
        reason: 'Supported by manufacturer datasheet.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-4',
        name: 'No-Load Speed',
        value: '0-400 / 0-1500 RPM',
        confidence: 95,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'No-load speed (1st gear / 2nd gear): 0 – 400 / 0 – 1,500 rpm',
        reason: 'Standardized unit normalization from OEM specification table.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-5',
        name: 'Maximum Torque',
        value: '30 Nm',
        confidence: 94,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Torque (soft/hard/max.): 14/30/- Nm',
        reason: 'Directly supported by manufacturer specification.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-6',
        name: 'Weight excl. Battery',
        value: '0.8 kg',
        confidence: 92,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Weight excl. battery: 0.80 kg',
        reason: 'Verified from OEM physical specifications.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-a-7',
        name: 'Certifications',
        value: null,
        confidence: 0,
        source: null,
        sourceUrl: '',
        evidence: null,
        reason: 'Zero-Hallucination: No certification evidence found in supplier or manufacturer documentation.',
        validationStatus: 'Not Found',
      },
    ],
    features: [
      {
        feature: '12 V cordless drill/driver.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Battery voltage: 12 V',
        confidence: 98,
        validationStatus: 'verified',
      },
      {
        feature: '10 mm keyless chuck.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Chuck capacity, min./max.: 0.8 / 10 mm keyless three-jaw chuck',
        confidence: 96,
        validationStatus: 'verified',
      },
      {
        feature: 'Two-speed no-load speed of 0–400 / 0–1500 RPM.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'No-load speed (1st gear / 2nd gear): 0 – 400 / 0 – 1,500 rpm',
        confidence: 95,
        validationStatus: 'verified',
      },
      {
        feature: 'Maximum torque rating of 30 Nm.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Torque (soft/hard/max.): 14/30/- Nm',
        confidence: 94,
        validationStatus: 'verified',
      },
      {
        feature: 'Electronic Cell Protection (ECP).',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Electronic Cell Protection (ECP) technology included',
        confidence: 95,
        validationStatus: 'verified',
      },
      {
        feature: 'Integrated LED work light.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Integrated LED illumination',
        confidence: 95,
        validationStatus: 'verified',
      },
    ],
    traceability: [
      {
        stage: 'Raw Supplier Input',
        source: 'supplier_data',
        evidence: 'Brand: Bosch | Part Number: GSR 120-LI | Description: "12v drill driver cordless"',
        decision: 'Extracted brand token "Bosch", MPN "GSR 120-LI", and raw spec "12v".',
        confidence: 100,
        validation: 'verified',
      },
      {
        stage: 'Product Identification',
        source: 'manufacturer',
        evidence: 'Matched exact OEM SKU GSR 120-LI in Bosch Power Tools Global Catalog.',
        decision: 'Exact match confirmed against official OEM catalog index.',
        confidence: 98,
        validation: 'verified',
      },
      {
        stage: 'Source/Context Retrieval',
        source: 'manufacturer',
        evidence: 'Retrieved verified OEM technical sheet (12V, 10mm chuck, 0-1500 RPM, 30Nm).',
        decision: 'Enriched verified physical and electrical specs from official datasheet.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Taxonomy Mapping',
        source: 'trusted_reference',
        evidence: 'Mapped to Power Tools > Drills > Cordless Drills.',
        decision: 'Assigned hierarchical path: Tools & Hardware > Power Tools > Drills > Cordless Drills.',
        confidence: 97,
        validation: 'verified',
      },
      {
        stage: 'Attribute Extraction',
        source: 'manufacturer',
        evidence: 'Extracted 6 verified technical attributes from manufacturer datasheet.',
        decision: 'Normalized voltage to "12 V", speed to "0-1500 RPM", and weight to "0.8 kg".',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Attribute Validation',
        source: 'knowledge_base',
        evidence: 'Cross-checked 12V Li-ion battery physics and 10mm chuck torque capacity.',
        decision: 'All attributes passed strict physical constraint validation. Unbacked certs marked "Not Found".',
        confidence: 95,
        validation: 'verified',
      },
      {
        stage: 'Confidence Scoring',
        source: 'knowledge_base',
        evidence: 'All extracted specs backed by official manufacturer documentation (92-98%).',
        decision: 'Calculated composite certainty score of 96%. Assigned High Confidence / Ready for Review status.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Final Catalog Generation',
        source: 'manufacturer',
        evidence: 'Extracted 6 validated attributes; 1 unsupported attribute marked Not Found.',
        decision: 'Validated product record with evidence-backed features; marked Ready for Review.',
        confidence: 96,
        validation: 'verified',
      },
    ],
  },

  // 2. TEST B: Incomplete Product (Zero Hallucination Test)
  {
    id: 'prod-test-b',
    brand: 'Unknown',
    partNumber: 'ABC-123',
    inputDescription: 'industrial tool',
    productTitle: 'Unknown ABC-123 Industrial Tool',
    category: ['Industrial Supplies & Tools', 'General Tools'],
    categoryPath: 'Industrial Supplies & Tools > General Tools',
    categoryStatus: 'Needs Review',
    confidence: 34,
    status: 'Low Confidence',
    reviewStatus: 'Needs Review',
    processedAt: '2026-08-16T18:35:00Z',
    description:
      'Raw supplier record for unidentified part number ABC-123. Specifications cannot be verified against official OEM catalogs without additional manufacturer metadata.',
    productIdentification: {
      brand: 'Unknown',
      partNumber: 'ABC-123',
      matchedProduct: 'Unidentified Product ABC-123',
      matchType: 'uncertain',
      confidence: 30,
      evidence: 'No manufacturer catalog entry, GTIN, or OEM registration found for part ABC-123.',
      source: 'ai_inference',
      sourceUrl: '',
    },
    attributes: [
      {
        id: 'attr-b-1',
        name: 'Brand',
        value: 'Unknown',
        confidence: 40,
        source: 'supplier_data',
        sourceUrl: '',
        evidence: 'Supplier brand field: "Unknown"',
        reason: 'Brand is unspecified or generic.',
        validationStatus: 'inferred',
      },
      {
        id: 'attr-b-2',
        name: 'Part Number',
        value: 'ABC-123',
        confidence: 75,
        source: 'supplier_data',
        sourceUrl: '',
        evidence: 'Supplier part number: "ABC-123"',
        reason: 'Extracted verbatim from supplier manifest.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-b-3',
        name: 'Voltage Rating',
        value: null,
        confidence: 0,
        source: null,
        sourceUrl: '',
        evidence: null,
        reason: 'Zero-Hallucination Rule: Voltage was not provided and cannot be invented.',
        validationStatus: 'Not Found',
      },
      {
        id: 'attr-b-4',
        name: 'Chuck / Collet Size',
        value: null,
        confidence: 0,
        source: null,
        sourceUrl: '',
        evidence: null,
        reason: 'Zero-Hallucination Rule: Dimensions must not be fabricated.',
        validationStatus: 'Not Found',
      },
      {
        id: 'attr-b-5',
        name: 'Weight',
        value: null,
        confidence: 0,
        source: null,
        sourceUrl: '',
        evidence: null,
        reason: 'Zero-Hallucination Rule: Weight not found in supplier record.',
        validationStatus: 'Not Found',
      },
      {
        id: 'attr-b-6',
        name: 'Certifications',
        value: null,
        confidence: 0,
        source: null,
        sourceUrl: '',
        evidence: null,
        reason: 'Zero-Hallucination Rule: Certifications must never be assumed without proof.',
        validationStatus: 'Not Found',
      },
    ],
    features: [
      {
        feature: 'Part number ABC-123 recorded from supplier manifest.',
        source: 'supplier_data',
        sourceUrl: '',
        evidence: 'Supplier part number: "ABC-123"',
        confidence: 75,
        validationStatus: 'verified',
      },
    ],
    traceability: [
      {
        stage: 'Raw Supplier Input',
        source: 'supplier_data',
        evidence: 'Brand: Unknown | Part: ABC-123 | Description: "industrial tool"',
        decision: 'Received sparse, unverified supplier input string.',
        confidence: 50,
        validation: 'inferred',
      },
      {
        stage: 'Product Identification',
        source: 'ai_inference',
        evidence: 'No OEM registration found for part ABC-123.',
        decision: 'Flagged product match as uncertain. Prohibited speculative identification.',
        confidence: 30,
        validation: 'inferred',
      },
      {
        stage: 'Source/Context Retrieval',
        source: 'knowledge_base',
        evidence: 'No OEM technical datasheets available for ABC-123.',
        decision: 'Source retrieval status: Unavailable. Did not fabricate context.',
        confidence: 0,
        validation: 'not_found',
      },
      {
        stage: 'Taxonomy Mapping',
        source: 'ai_inference',
        evidence: 'Broad fallback category mapped from keyword "industrial tool".',
        decision: 'Assigned "Industrial Supplies & Tools > General Tools" (Needs Review).',
        confidence: 45,
        validation: 'inferred',
      },
      {
        stage: 'Attribute Extraction',
        source: 'knowledge_base',
        evidence: 'No valid technical specifications found in supplier string.',
        decision: 'Zero-Hallucination: Missing attributes marked as "Not Found" with 0% confidence.',
        confidence: 25,
        validation: 'inferred',
      },
      {
        stage: 'Attribute Validation',
        source: 'knowledge_base',
        evidence: 'Multiple required critical attributes are absent.',
        decision: 'Validation rule failed: Insufficient data completeness for auto-approval.',
        confidence: 30,
        validation: 'inferred',
      },
      {
        stage: 'Confidence Scoring',
        source: 'knowledge_base',
        evidence: 'Evidence quality is minimal with uncertain product identification.',
        decision: 'Calculated low confidence of 34%. Product routed to human review queue.',
        confidence: 34,
        validation: 'inferred',
      },
      {
        stage: 'Final Catalog Generation',
        source: 'ai_inference',
        evidence: 'Processed 6 catalog fields with 4 unverified fields marked Not Found.',
        decision: 'Status set to Needs Review due to low confidence and missing specifications.',
        confidence: 34,
        validation: 'inferred',
      },
    ],
  },

  // 3. TEST C: Conflicting Data Test
  {
    id: 'prod-test-c',
    brand: 'Bosch',
    partNumber: 'GSR 120-LI',
    inputDescription: '18v heavy duty cordless drill driver brushless',
    productTitle: 'Bosch GSR 120-LI Professional Cordless Drill Driver [Data Conflict: 18V vs 12V]',
    category: ['Tools & Hardware', 'Power Tools', 'Drills', 'Cordless Drills'],
    categoryPath: 'Tools & Hardware > Power Tools > Drills > Cordless Drills',
    categoryStatus: 'Verified',
    confidence: 58,
    status: 'Medium Confidence',
    reviewStatus: 'Needs Review',
    processedAt: '2026-08-16T18:40:00Z',
    description:
      'Bosch GSR 120-LI cordless drill driver. Note: A data conflict exists between supplier input ("18v") and official manufacturer technical specifications ("12 V"). Requires catalog specialist resolution.',
    productIdentification: {
      brand: 'Bosch',
      partNumber: 'GSR 120-LI',
      matchedProduct: 'Bosch GSR 120-LI Professional Cordless Drill/Driver',
      matchType: 'exact',
      confidence: 96,
      evidence: 'Matched OEM part number GSR 120-LI in Bosch Power Tools Professional catalog.',
      source: 'manufacturer',
      sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
    },
    attributes: [
      {
        id: 'attr-c-1',
        name: 'Voltage Rating',
        value: '12 V (OEM) vs 18 V (Supplier)',
        confidence: 50,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Supplier description says "18v", but manufacturer OEM datasheet for GSR 120-LI explicitly specifies 12 V.',
        reason: 'CONFLICT DETECTED: Supplier input contradicts official manufacturer specification. Flagged for review rather than silently overriding.',
        validationStatus: 'conflicting',
      },
      {
        id: 'attr-c-2',
        name: 'Chuck Size',
        value: '10 mm',
        confidence: 96,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Chuck capacity: 0.8–10 mm',
        reason: 'Directly supported by manufacturer technical specification.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-c-3',
        name: 'Motor Type',
        value: 'Standard High-Efficiency Motor (Supplier claims Brushless)',
        confidence: 52,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Supplier description claimed "brushless", but base GSR 120-LI is a brushed 2-pole unit (Brushless version is GSR 12V-30/35).',
        reason: 'CONFLICT DETECTED: Supplier description motor claim contradicts OEM technical architecture.',
        validationStatus: 'conflicting',
      },
      {
        id: 'attr-c-4',
        name: 'Battery Platform',
        value: 'Bosch Professional 12V System',
        confidence: 95,
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Standard Bosch 12V Li-ion battery pack compatibility.',
        reason: 'Verified OEM battery architecture.',
        validationStatus: 'verified',
      },
    ],
    features: [
      {
        feature: '10 mm keyless chuck.',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Chuck capacity: 0.8–10 mm',
        confidence: 96,
        validationStatus: 'verified',
      },
      {
        feature: 'Electronic Cell Protection (ECP).',
        source: 'manufacturer',
        sourceUrl: 'https://www.bosch-professional.com/products/gsr-120-li-06019G8000',
        evidence: 'Electronic Cell Protection (ECP)',
        confidence: 95,
        validationStatus: 'verified',
      },
    ],
    traceability: [
      {
        stage: 'Raw Supplier Input',
        source: 'supplier_data',
        evidence: 'Brand: Bosch | Part: GSR 120-LI | Description: "18v heavy duty cordless drill driver brushless"',
        decision: 'Ingested raw supplier string containing "18v" and "brushless" keywords.',
        confidence: 100,
        validation: 'verified',
      },
      {
        stage: 'Product Identification',
        source: 'manufacturer',
        evidence: 'Identified exact match: Bosch GSR 120-LI in OEM database.',
        decision: 'Matched to official manufacturer master SKU.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Source/Context Retrieval',
        source: 'manufacturer',
        evidence: 'Retrieved verified OEM datasheet showing 12V rating and standard brushed architecture.',
        decision: 'Retrieved ground truth specification parameters.',
        confidence: 98,
        validation: 'verified',
      },
      {
        stage: 'Taxonomy Mapping',
        source: 'trusted_reference',
        evidence: 'Mapped to Cordless Drills category.',
        decision: 'Assigned: Tools & Hardware > Power Tools > Drills > Cordless Drills.',
        confidence: 95,
        validation: 'verified',
      },
      {
        stage: 'Attribute Extraction',
        source: 'manufacturer',
        evidence: 'Discrepancy detected between supplier text (18V, brushless) and OEM specs (12V, brushed).',
        decision: 'Preserved both claims and recorded evidence of conflict.',
        confidence: 50,
        validation: 'conflicting',
      },
      {
        stage: 'Attribute Validation',
        source: 'knowledge_base',
        evidence: 'Supplier claim contradicts manufacturer ground truth.',
        decision: 'Flagged validationStatus = "conflicting". Did not silently overwrite without audit trail.',
        confidence: 52,
        validation: 'conflicting',
      },
      {
        stage: 'Confidence Scoring',
        source: 'knowledge_base',
        evidence: 'Penalized overall confidence due to unresolved attribute conflicts.',
        decision: 'Score set to 58% (Medium Confidence / Needs Review). Prevented auto-approval.',
        confidence: 58,
        validation: 'conflicting',
      },
      {
        stage: 'Final Catalog Generation',
        source: 'ai_inference',
        evidence: 'Processed 4 catalog fields with 2 conflicting attributes detected.',
        decision: 'Catalog status set to Needs Review with conflict warnings for catalog specialist.',
        confidence: 58,
        validation: 'conflicting',
      },
    ],
  },

  // 4. Makita DHP482
  {
    id: 'prod-002',
    brand: 'Makita',
    partNumber: 'DHP482',
    inputDescription: '18v cordless hammer drill bare tool',
    productTitle: 'Makita DHP482Z 18V LXT Cordless Combi Hammer Drill Driver',
    category: ['Tools & Hardware', 'Power Tools', 'Hammer Drills', 'Cordless Hammer Drills'],
    categoryPath: 'Tools & Hardware > Power Tools > Hammer Drills > Cordless Hammer Drills',
    categoryStatus: 'Verified',
    confidence: 96,
    status: 'Ready for Review',
    reviewStatus: 'Validated',
    processedAt: '2026-08-16T18:24:00Z',
    description:
      'Makita DHP482 18 V LXT cordless combi drill featuring all-metal gear construction, twin LED work lights, and Extreme Protection Technology (XPT).',
    productIdentification: {
      brand: 'Makita',
      partNumber: 'DHP482',
      matchedProduct: 'Makita DHP482 18V LXT Combi Drill',
      matchType: 'exact',
      confidence: 98,
      evidence: 'Exact OEM model match in Makita Global Power Tools Catalog.',
      source: 'manufacturer',
      sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
    },
    attributes: [
      {
        id: 'attr-mak-1',
        name: 'Voltage Rating',
        value: '18 V',
        confidence: 98,
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Nominal Battery Voltage: 18 V LXT Platform',
        reason: 'Directly supported by manufacturer specification.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-mak-2',
        name: 'Chuck Size',
        value: '13 mm (1/2 in)',
        confidence: 96,
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Drill chuck capacity: 1.5 - 13 mm',
        reason: 'Supported by manufacturer technical sheet.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-mak-3',
        name: 'Max Fastening Torque',
        value: '62 Nm',
        confidence: 95,
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Max Fastening Torque (Hard / Soft): 62 / 36 Nm',
        reason: 'Supported by official OEM specification table.',
        validationStatus: 'verified',
      },
      {
        id: 'attr-mak-4',
        name: 'Impact Rate',
        value: '0-9000 / 0-28500 IPM',
        confidence: 94,
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Impacts per minute (IPM): Low 0-9,000, High 0-28,500',
        reason: 'Normalized impact rate measurement from datasheet.',
        validationStatus: 'verified',
      },
    ],
    features: [
      {
        feature: '18 V LXT cordless platform.',
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Nominal Battery Voltage: 18 V LXT Platform',
        confidence: 98,
        validationStatus: 'verified',
      },
      {
        feature: '13 mm keyless chuck.',
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Drill chuck capacity: 1.5 - 13 mm',
        confidence: 96,
        validationStatus: 'verified',
      },
      {
        feature: 'Two-speed variable transmission (0–600 / 0–1900 RPM).',
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'No load speed: Low 0-600 rpm, High 0-1,900 rpm',
        confidence: 95,
        validationStatus: 'verified',
      },
      {
        feature: 'Extreme Protection Technology (XPT).',
        source: 'manufacturer',
        sourceUrl: 'https://www.makitatools.com/products/details/DHP482Z',
        evidence: 'Extreme Protection Technology (XPT) engineered into housing',
        confidence: 95,
        validationStatus: 'verified',
      },
    ],
    traceability: [
      {
        stage: 'Raw Supplier Input',
        source: 'supplier_data',
        evidence: 'Brand: Makita | Part: DHP482 | Desc: "18v cordless hammer drill bare tool"',
        decision: 'Extracted brand token "Makita", MPN "DHP482", and spec "18v".',
        confidence: 100,
        validation: 'verified',
      },
      {
        stage: 'Product Identification',
        source: 'manufacturer',
        evidence: 'Matched OEM part DHP482 in Makita Global Master Catalog.',
        decision: 'Confirmed exact model identity.',
        confidence: 98,
        validation: 'verified',
      },
      {
        stage: 'Source/Context Retrieval',
        source: 'manufacturer',
        evidence: 'Retrieved verified technical datasheet from manufacturer.',
        decision: 'Extracted 18V LXT platform specs and torque tables.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Taxonomy Mapping',
        source: 'trusted_reference',
        evidence: 'Mapped to Cordless Hammer Drills hierarchy.',
        decision: 'Tools & Hardware > Power Tools > Hammer Drills > Cordless Hammer Drills.',
        confidence: 97,
        validation: 'verified',
      },
      {
        stage: 'Attribute Extraction',
        source: 'manufacturer',
        evidence: 'Extracted 4 standardized technical specs.',
        decision: 'Normalized voltage to 18 V and torque to 62 Nm.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Attribute Validation',
        source: 'knowledge_base',
        evidence: 'Passed all mechanical and electrical consistency tests.',
        decision: 'Attributes verified against OEM specifications.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Confidence Scoring',
        source: 'knowledge_base',
        evidence: 'High evidence quality across all fields.',
        decision: 'Calculated 96% composite confidence score.',
        confidence: 96,
        validation: 'verified',
      },
      {
        stage: 'Final Catalog Generation',
        source: 'manufacturer',
        evidence: 'Processed 4 verified attributes.',
        decision: 'Validated product record; marked Ready for Review.',
        confidence: 96,
        validation: 'verified',
      },
    ],
  },
];

export const ANALYTICS_DATA = {
  totalProcessed: 1420,
  highConfidenceCount: 1285,
  mediumConfidenceCount: 95,
  needsReviewCount: 40,
  averageConfidence: 94.6,
  attributesExtracted: 8940,
  accuracyRate: 99.2,
};
